### PR TITLE
Add usage notice in readme file

### PR DESCRIPTION
**Pull request by brettaufheber**

### CODE REVIEW

**Comment by pathob** [comment]
Good start, but my main concern still exists: A cache should clean up old entries at some point and it's not documented whether or how that works.

**Comment by brettaufheber** [comment]
@pathob 
I added a notice in the readme that there is currently no cleanup mechanism implemented.

For this purpose i created a an issue: https://github.com/aservo/docker-artifact-resolution/issues/11

**Review by gebae — APPROVED** [review]
In principle it is ok for me, but:
* A hint in the readme, how the cache entry hash is calculated, could be helpful for the users.
* It is not 100% clear, if the "parameters for all artifact types" can be used together with the resolve-using-config task. If yes, it would mean that the documentation of the cache-dir parameter for the resolve-using-config task is redundant. 
* It is also not clear, if  the cache-dir parameter can be part of the  JSON config file (why not, actually?).

**Comment by brettaufheber** [comment]
Hello @gebae,
thank you for your review.
I will improve the readme file according to your suggestions.

**Pull request merged**
